### ISSUE TITLE
More default shrubs

### ISSUE THREAD

**Issue by ST-DDT** [Lhykos/OreShrubs#11]
Could you also include shrubs for Redstone and Glowstone by default?

Both could glow by default like the experience bush.

For redstone bush I'm not sure where they could spawn by default, maybe in the mesa biome and growing on red wool or red glas or red sand. I'm not sure about their berries either, maybe some redstone crumb (1/9 of dust).

For Glowstone maybe they have to grow in daylight (each grow stage toggles the light requirement), but on the other hand they also dont decay from too much light. Or they require the exact light level of the nether.

Also there should be `diamond` (grow on stationary lava or a block of diamond) and `emerald` bushes (requires absolute darkness+obsidian) which are solely sold by villagers for a painful amount (7-15) of blocks of emerald.

That way I could supply my city server with "infinite" resource sources in a limited amount of space.

I know I can probably use the custom bush settings for most of it, but if metal and quartz can grow out of nothing then crystals can as well.

**Comment by Lhykos** [comment]
I just want to give a minimal support for some ores, mostly vanilla and ores that the most mods use like copper, tin and so on.
I understand what you mean, why he support quartz but no diamond shrubs?

In the next update I will change a lot and it could be possible that I support all vanilla ores, maybe you will get them not that easy as before, because personally it ruin the game experience if you see these shrubs every few blocks in a cave, they should be rare. 

I gave the support for custom shrubs for exactly that case! I never can support all possible ores by default. For the time being you should use the custom shrubs and wait for the next update. :)

**Comment by Lhykos** [comment]
I add two more in 1.4.1. More is comming soon! :)
